# Generated by Django 5.0.1 on 2024-01-09 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('id_telegram', models.CharField(max_length=10)),
                ('cantidad', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(max_length=10)),
                ('nombres_apellidos', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram', models.BooleanField()),
                ('id_telegram', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=20, null=True)),
                ('provincia', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.BinaryField()),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('id_proveedor', models.IntegerField()),
                ('ruc_proveedor', models.CharField(max_length=13)),
                ('n_comprobante', models.SmallIntegerField()),
                ('fecha', models.DateField()),
                ('IVA', models.SmallIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_proveedor', models.CharField(max_length=13)),
                ('Nombres', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('credito', models.BooleanField()),
                ('Telefono', models.CharField(max_length=10)),
                ('contacto_nombre_apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id_telegram', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('activo', models.BooleanField()),
                ('telefono', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.IntegerField()),
                ('nombres_apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('n_comprobante', models.SmallIntegerField()),
                ('fecha', models.DateField()),
                ('IVA', models.SmallIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('estado', models.CharField(max_length=20)),
                ('forma_pago', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
                ('precioventa', models.DecimalField(decimal_places=2, max_digits=11)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria')),
                ('id_imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.imagen')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.IntegerField()),
                ('cantidad', models.SmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ingreso', models.IntegerField()),
                ('cantidad', models.SmallIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.IntegerField()),
                ('nombres_apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile_images')),
                ('usuario1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
