# Generated by Django 5.0.1 on 2024-01-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usuario1',
            new_name='user',
        ),
    ]
