# Generated by Django 5.0.1 on 2024-01-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_usuario1_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
