# Generated by Django 5.0.1 on 2024-01-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_profile_image_profile_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_data',
        ),
    ]
