# Generated by Django 5.0.1 on 2024-01-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_profile_image_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_rol',
        ),
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
