# Generated by Django 5.0.1 on 2024-01-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_cliente_id_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telegram',
            field=models.BooleanField(null=True),
        ),
    ]
